workflows:
  # iOS Build Workflow
  build-ios:
    name: Build iOS App
    max_build_duration: 60
    environment:
      flutter: 3.27.4
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Generate code
        script: |
          flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Run tests
        script: |
          flutter test || echo "No tests found, continuing..."
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Create iOS IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r -y Runner.ipa Payload/
          rm -rf Payload
          echo "iOS build completed successfully"
          unzip -l Runner.ipa | head -10
    artifacts:
      - build/ios/iphoneos/Runner.ipa
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - a1392819747@gmail.com
        notify:
          success: true
          failure: false

  # Android Build Workflow
  build-android:
    name: Build Android App
    max_build_duration: 60
    environment:
      flutter: 3.27.4
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Fix plugin namespaces
        script: |
          echo "修复第三方插件的namespace问题..."
          
          # 修复 flutter_keyboard_visibility
          if [ -f "$HOME/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility-5.4.1/android/build.gradle" ]; then
            echo "修复 flutter_keyboard_visibility..."
            sed -i 's/android {/android {\n    namespace '\''com.jrai.flutter_keyboard_visibility'\''/' "$HOME/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility-5.4.1/android/build.gradle"
          fi
          
          # 修复 flutter_openim_sdk
          if [ -f "$HOME/.pub-cache/hosted/pub.dev/flutter_openim_sdk-3.8.3+3/android/build.gradle" ]; then
            echo "修复 flutter_openim_sdk..."
            sed -i 's/android {/android {\n    namespace '\''io.openim.flutter_openim_sdk'\''/' "$HOME/.pub-cache/hosted/pub.dev/flutter_openim_sdk-3.8.3+3/android/build.gradle"
          fi
          
          # 修复 flutter_sensors
          if [ -f "$HOME/.pub-cache/hosted/pub.dev/flutter_sensors-1.0.1/android/build.gradle" ]; then
            echo "修复 flutter_sensors..."
            sed -i 's/android {/android {\n    namespace '\''com.example.fluttersensors'\''/' "$HOME/.pub-cache/hosted/pub.dev/flutter_sensors-1.0.1/android/build.gradle"
          fi
          
          # 修复 scan
          if [ -f "$HOME/.pub-cache/hosted/pub.dev/scan-1.6.0/android/build.gradle" ]; then
            echo "修复 scan..."
            sed -i 's/android {/android {\n    namespace '\''com.chavesgu.scan'\''/' "$HOME/.pub-cache/hosted/pub.dev/scan-1.6.0/android/build.gradle"
          fi
          
          # 修复 sound_mode
          if [ -f "$HOME/.pub-cache/hosted/pub.dev/sound_mode-2.0.2/android/build.gradle" ]; then
            echo "修复 sound_mode..."
            sed -i 's/android {/android {\n    namespace '\''com.tryingoutsomething.soundmode.sound_mode'\''/' "$HOME/.pub-cache/hosted/pub.dev/sound_mode-2.0.2/android/build.gradle"
          fi
          
          # 修复 uri_to_file
          if [ -f "$HOME/.pub-cache/hosted/pub.dev/uri_to_file-1.0.0/android/build.gradle" ]; then
            echo "修复 uri_to_file..."
            sed -i 's/android {/android {\n    namespace '\''in.lazymanstudios.uri_to_file'\''/' "$HOME/.pub-cache/hosted/pub.dev/uri_to_file-1.0.0/android/build.gradle"
          fi
          
          echo "修复完成！"
      - name: Generate code
        script: |
          flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Run tests
        script: |
          flutter test || echo "No tests found, continuing..."
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build Android AAB
        script: |
          flutter build appbundle --release
      - name: Verify builds
        script: |
          echo "Android builds completed successfully"
          ls -la build/app/outputs/flutter-apk/
          ls -la build/app/outputs/bundle/release/
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - a1392819747@gmail.com
        notify:
          success: true
          failure: false

  # Combined Build Workflow - iOS and Android
  build-all:
    name: Build All Platforms (iOS + Android)
    max_build_duration: 90
    environment:
      flutter: 3.27.4
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Fix plugin namespaces
        script: |
          echo "修复第三方插件的namespace问题..."
          
          # 修复 flutter_keyboard_visibility
          if [ -f "$HOME/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility-5.4.1/android/build.gradle" ]; then
            echo "修复 flutter_keyboard_visibility..."
            sed -i 's/android {/android {\n    namespace '\''com.jrai.flutter_keyboard_visibility'\''/' "$HOME/.pub-cache/hosted/pub.dev/flutter_keyboard_visibility-5.4.1/android/build.gradle"
          fi
          
          # 修复 flutter_openim_sdk
          if [ -f "$HOME/.pub-cache/hosted/pub.dev/flutter_openim_sdk-3.8.3+3/android/build.gradle" ]; then
            echo "修复 flutter_openim_sdk..."
            sed -i 's/android {/android {\n    namespace '\''io.openim.flutter_openim_sdk'\''/' "$HOME/.pub-cache/hosted/pub.dev/flutter_openim_sdk-3.8.3+3/android/build.gradle"
          fi
          
          # 修复 flutter_sensors
          if [ -f "$HOME/.pub-cache/hosted/pub.dev/flutter_sensors-1.0.1/android/build.gradle" ]; then
            echo "修复 flutter_sensors..."
            sed -i 's/android {/android {\n    namespace '\''com.example.fluttersensors'\''/' "$HOME/.pub-cache/hosted/pub.dev/flutter_sensors-1.0.1/android/build.gradle"
          fi
          
          # 修复 scan
          if [ -f "$HOME/.pub-cache/hosted/pub.dev/scan-1.6.0/android/build.gradle" ]; then
            echo "修复 scan..."
            sed -i 's/android {/android {\n    namespace '\''com.chavesgu.scan'\''/' "$HOME/.pub-cache/hosted/pub.dev/scan-1.6.0/android/build.gradle"
          fi
          
          # 修复 sound_mode
          if [ -f "$HOME/.pub-cache/hosted/pub.dev/sound_mode-2.0.2/android/build.gradle" ]; then
            echo "修复 sound_mode..."
            sed -i 's/android {/android {\n    namespace '\''com.tryingoutsomething.soundmode.sound_mode'\''/' "$HOME/.pub-cache/hosted/pub.dev/sound_mode-2.0.2/android/build.gradle"
          fi
          
          # 修复 uri_to_file
          if [ -f "$HOME/.pub-cache/hosted/pub.dev/uri_to_file-1.0.0/android/build.gradle" ]; then
            echo "修复 uri_to_file..."
            sed -i 's/android {/android {\n    namespace '\''in.lazymanstudios.uri_to_file'\''/' "$HOME/.pub-cache/hosted/pub.dev/uri_to_file-1.0.0/android/build.gradle"
          fi
          
          echo "修复完成！"
      - name: Generate code
        script: |
          flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Run tests
        script: |
          flutter test || echo "No tests found, continuing..."
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build Android AAB
        script: |
          flutter build appbundle --release
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Create iOS IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r -y Runner.ipa Payload/
          rm -rf Payload
          echo "All builds completed successfully"
          unzip -l Runner.ipa | head -10
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/iphoneos/Runner.ipa
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - a1392819747@gmail.com
        notify:
          success: true
          failure: false