workflows:
  # iOS Build Workflow
  build-ios:
    name: Build iOS App
    max_build_duration: 60
    environment:
      flutter: 3.27.4
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Generate code
        script: |
          flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Run tests
        script: |
          flutter test || echo "No tests found, continuing..."
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Create iOS IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r -y Runner.ipa Payload/
          rm -rf Payload
          echo "iOS build completed successfully"
          unzip -l Runner.ipa | head -10
    artifacts:
      - build/ios/iphoneos/Runner.ipa
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - a1392819747@gmail.com
        notify:
          success: true
          failure: false

  # Android Build Workflow
  build-android:
    name: Build Android App
    max_build_duration: 60
    environment:
      flutter: 3.27.4
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Fix plugin namespaces
        script: |
          echo "=== 开始修复插件namespace问题 ==="
          
          # 设置插件路径
          PUB_CACHE="$HOME/.pub-cache/hosted/pub.dev"
          
          # 修复 flutter_keyboard_visibility
          echo "修复 flutter_keyboard_visibility..."
          KEYBOARD_VISIBILITY_PATH="$PUB_CACHE/flutter_keyboard_visibility-5.4.1/android/build.gradle"
          if [ -f "$KEYBOARD_VISIBILITY_PATH" ]; then
            echo "找到文件: $KEYBOARD_VISIBILITY_PATH"
            # 直接使用sed添加namespace
            sed -i.bak 's/android {/android {\n    namespace "com.jrai.flutter_keyboard_visibility"/' "$KEYBOARD_VISIBILITY_PATH"
            echo "flutter_keyboard_visibility 修复完成"
          else
            echo "flutter_keyboard_visibility 文件不存在"
          fi
          
          # 修复 flutter_openim_sdk
          echo "修复 flutter_openim_sdk..."
          OPENIM_SDK_PATH="$PUB_CACHE/flutter_openim_sdk-3.8.3+3/android/build.gradle"
          if [ -f "$OPENIM_SDK_PATH" ]; then
            echo "找到文件: $OPENIM_SDK_PATH"
            sed -i.bak 's/android {/android {\n    namespace "io.openim.flutter_openim_sdk"/' "$OPENIM_SDK_PATH"
            echo "flutter_openim_sdk 修复完成"
          else
            echo "flutter_openim_sdk 文件不存在"
          fi
          
          # 修复 flutter_sensors
          echo "修复 flutter_sensors..."
          SENSORS_PATH="$PUB_CACHE/flutter_sensors-1.0.1/android/build.gradle"
          if [ -f "$SENSORS_PATH" ]; then
            echo "找到文件: $SENSORS_PATH"
            sed -i.bak 's/android {/android {\n    namespace "com.example.fluttersensors"/' "$SENSORS_PATH"
            echo "flutter_sensors 修复完成"
          else
            echo "flutter_sensors 文件不存在"
          fi
          
          # 修复 scan
          echo "修复 scan..."
          SCAN_PATH="$PUB_CACHE/scan-1.6.0/android/build.gradle"
          if [ -f "$SCAN_PATH" ]; then
            echo "找到文件: $SCAN_PATH"
            sed -i.bak 's/android {/android {\n    namespace "com.chavesgu.scan"/' "$SCAN_PATH"
            echo "scan 修复完成"
          else
            echo "scan 文件不存在"
          fi
          
          # 修复 sound_mode
          echo "修复 sound_mode..."
          SOUND_MODE_PATH="$PUB_CACHE/sound_mode-2.0.2/android/build.gradle"
          if [ -f "$SOUND_MODE_PATH" ]; then
            echo "找到文件: $SOUND_MODE_PATH"
            sed -i.bak 's/android {/android {\n    namespace "com.tryingoutsomething.soundmode.sound_mode"/' "$SOUND_MODE_PATH"
            echo "sound_mode 修复完成"
          else
            echo "sound_mode 文件不存在"
          fi
          
          # 修复 uri_to_file
          echo "修复 uri_to_file..."
          URI_TO_FILE_PATH="$PUB_CACHE/uri_to_file-1.0.0/android/build.gradle"
          if [ -f "$URI_TO_FILE_PATH" ]; then
            echo "找到文件: $URI_TO_FILE_PATH"
            sed -i.bak 's/android {/android {\n    namespace "in.lazymanstudios.uri_to_file"/' "$URI_TO_FILE_PATH"
            echo "uri_to_file 修复完成"
          else
            echo "uri_to_file 文件不存在"
          fi
          
          echo "=== 所有插件namespace修复完成 ==="
      - name: Generate code
        script: |
          flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Run tests
        script: |
          flutter test || echo "No tests found, continuing..."
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build Android AAB
        script: |
          flutter build appbundle --release
      - name: Verify builds
        script: |
          echo "Android builds completed successfully"
          ls -la build/app/outputs/flutter-apk/
          ls -la build/app/outputs/bundle/release/
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - a1392819747@gmail.com
        notify:
          success: true
          failure: false

  # Combined Build Workflow - iOS and Android
  build-all:
    name: Build All Platforms (iOS + Android)
    max_build_duration: 90
    environment:
      flutter: 3.27.4
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Fix plugin namespaces
        script: |
          echo "=== 开始修复插件namespace问题 ==="
          
          # 设置插件路径
          PUB_CACHE="$HOME/.pub-cache/hosted/pub.dev"
          
          # 修复 flutter_keyboard_visibility
          echo "修复 flutter_keyboard_visibility..."
          KEYBOARD_VISIBILITY_PATH="$PUB_CACHE/flutter_keyboard_visibility-5.4.1/android/build.gradle"
          if [ -f "$KEYBOARD_VISIBILITY_PATH" ]; then
            echo "找到文件: $KEYBOARD_VISIBILITY_PATH"
            # 直接使用sed添加namespace
            sed -i.bak 's/android {/android {\n    namespace "com.jrai.flutter_keyboard_visibility"/' "$KEYBOARD_VISIBILITY_PATH"
            echo "flutter_keyboard_visibility 修复完成"
          else
            echo "flutter_keyboard_visibility 文件不存在"
          fi
          
          # 修复 flutter_openim_sdk
          echo "修复 flutter_openim_sdk..."
          OPENIM_SDK_PATH="$PUB_CACHE/flutter_openim_sdk-3.8.3+3/android/build.gradle"
          if [ -f "$OPENIM_SDK_PATH" ]; then
            echo "找到文件: $OPENIM_SDK_PATH"
            sed -i.bak 's/android {/android {\n    namespace "io.openim.flutter_openim_sdk"/' "$OPENIM_SDK_PATH"
            echo "flutter_openim_sdk 修复完成"
          else
            echo "flutter_openim_sdk 文件不存在"
          fi
          
          # 修复 flutter_sensors
          echo "修复 flutter_sensors..."
          SENSORS_PATH="$PUB_CACHE/flutter_sensors-1.0.1/android/build.gradle"
          if [ -f "$SENSORS_PATH" ]; then
            echo "找到文件: $SENSORS_PATH"
            sed -i.bak 's/android {/android {\n    namespace "com.example.fluttersensors"/' "$SENSORS_PATH"
            echo "flutter_sensors 修复完成"
          else
            echo "flutter_sensors 文件不存在"
          fi
          
          # 修复 scan
          echo "修复 scan..."
          SCAN_PATH="$PUB_CACHE/scan-1.6.0/android/build.gradle"
          if [ -f "$SCAN_PATH" ]; then
            echo "找到文件: $SCAN_PATH"
            sed -i.bak 's/android {/android {\n    namespace "com.chavesgu.scan"/' "$SCAN_PATH"
            echo "scan 修复完成"
          else
            echo "scan 文件不存在"
          fi
          
          # 修复 sound_mode
          echo "修复 sound_mode..."
          SOUND_MODE_PATH="$PUB_CACHE/sound_mode-2.0.2/android/build.gradle"
          if [ -f "$SOUND_MODE_PATH" ]; then
            echo "找到文件: $SOUND_MODE_PATH"
            sed -i.bak 's/android {/android {\n    namespace "com.tryingoutsomething.soundmode.sound_mode"/' "$SOUND_MODE_PATH"
            echo "sound_mode 修复完成"
          else
            echo "sound_mode 文件不存在"
          fi
          
          # 修复 uri_to_file
          echo "修复 uri_to_file..."
          URI_TO_FILE_PATH="$PUB_CACHE/uri_to_file-1.0.0/android/build.gradle"
          if [ -f "$URI_TO_FILE_PATH" ]; then
            echo "找到文件: $URI_TO_FILE_PATH"
            sed -i.bak 's/android {/android {\n    namespace "in.lazymanstudios.uri_to_file"/' "$URI_TO_FILE_PATH"
            echo "uri_to_file 修复完成"
          else
            echo "uri_to_file 文件不存在"
          fi
          
          echo "=== 所有插件namespace修复完成 ==="
      - name: Generate code
        script: |
          flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Run tests
        script: |
          flutter test || echo "No tests found, continuing..."
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build Android AAB
        script: |
          flutter build appbundle --release
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Create iOS IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r -y Runner.ipa Payload/
          rm -rf Payload
          echo "All builds completed successfully"
          unzip -l Runner.ipa | head -10
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build/ios/iphoneos/Runner.ipa
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - a1392819747@gmail.com
        notify:
          success: true
          failure: false