name: Android Simple Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android-simple:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.4'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Generate code
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
    
    - name: Run tests
      run: flutter test || echo "No tests found, continuing..."
    
    - name: Build APK (no signing)
      run: flutter build apk --release
    
    - name: Build AAB (no signing)
      run: flutter build appbundle --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk-simple
        path: build/app/outputs/flutter-apk/app-release.apk
    
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: android-aab-simple
        path: build/app/outputs/bundle/release/app-release.aab
