name: iOS Simple Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios-simple:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.4'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Generate code
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
    
    - name: Run tests
      run: flutter test || echo "No tests found, continuing..."
    
    - name: Build iOS without codesign
      run: flutter build ios --no-codesign
    
    - name: Create IPA manually
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        # Create IPA with proper compression
        zip -r -y Runner.ipa Payload/
        # Clean up temporary directory
        rm -rf Payload
        # Verify IPA structure
        unzip -l Runner.ipa | head -10
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa-simple
        path: build/ios/iphoneos/Runner.ipa
    
    - name: Upload App Bundle (for Xcode)
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-bundle-for-xcode
        path: build/ios/iphoneos/Runner.app
